const ADMIN = "ADMIN";
const EXAMINER = "EXAMINER";
const STUDENT = "STUDENT";
const APPROVED = "APPROVED";
const DELETED = "DELETED";
const DECLINED = "DECLINED";

export { ADMIN, EXAMINER, STUDENT, APPROVED, DELETED, DECLINED };
